# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='归属板块')),
            ],
        ),
        migrations.AlterField(
            model_name='gamekind',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='游戏名字'),
        ),
        migrations.AlterField(
            model_name='gamekind',
            name='type',
            field=models.CharField(max_length=255, verbose_name='游戏性质'),
        ),
        migrations.AddField(
            model_name='gamekind',
            name='kind',
            field=models.ManyToManyField(to='mytest.GameFor'),
        ),
    ]
