# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_auto_20190506_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamekind',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='game_img'),
        ),
    ]
