# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_auto_20190506_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('desc', models.CharField(max_length=50, verbose_name='发售公司及平台')),
                ('time', models.DateField(verbose_name='发表日期')),
                ('smallimg', models.ImageField(blank=True, default=None, null=True, upload_to='small_img')),
                ('bigimg', models.ImageField(blank=True, default=None, null=True, upload_to='big_img')),
                ('videourl', models.CharField(max_length=255, verbose_name='网址')),
            ],
        ),
    ]
